### ISSUE TITLE
How to use this repo?

### ISSUE THREAD

**Issue by ehaoxiongdiycw** [jet/baybars#12]
I want to test this repo, but i don't know how to start.

Is there some documents?

**Comment by bugra** [comment]
@ehaoxiongdiycw I will add some README around this as well as documentation, but you can get the package from `pip`:
`pip3 install baybars`

Are you interested in a specific module?

**Comment by ehaoxiongdiycw** [comment]
I just want to do some security test for bug bounty. But I don't know how to start this repo. So I posted an issue.

Is this repo has some service?

**Comment by bugra** [comment]
It does not have a service.

**Comment by bugra** [comment]
@ehaoxiongdiycw Can I close this issue if you do not have further questions/comments?
